### ISSUE TITLE
eBay and Lastpass have fixed the quirks that allowed this script to function

### ISSUE THREAD

**Issue by boyesm** [martinvigo/email2phonenumber#22]
Lastpass has a captcha: https://lastpass.com/recover.php
eBay no longer included phone numbers in password reset messages.

Although this maybe obvious to some, just wanted to let users know.

**Comment by martinvigo** [comment]
Yep, OSINT tools tend to break quickly due to UI changes or additional protections. email2phonenumber was meant as a PoC. I wrote phonerator instead, focusing solely on the generation of valid phone numbers:

https://www.martinvigo.com/phonerator-an-advanced-valid-phone-number-generator/
https://www.martinvigo.com/tools/phonerator/
