### ISSUE TITLE
Irritating and doesn't work.

### ISSUE THREAD

**Issue by ghost** [martinvigo/email2phonenumber#38]
I have been fooling with this for 6 hours and I'm DONE!!! So exhausting and confusing. First of all, the directions were absolutely TERRIBLE AND THE YOUTUBE VIDEOS DID NOT HELP AT ALL!!!!

When I FINALLY got to run the scrape, I get the error message "Failed to resolve 'fyp.ebay.com' ([Errno 11001]" something is going on with ebay to where it won't even run anything else. I am so defeated. Just take this crap down at this point, jesus christ...unless someone knows how ti fix it.

**Comment by Weffy61** [comment]
> I have been fooling with this for 6 hours and I'm DONE!!! So exhausting and confusing. First of all, the directions were absolutely TERRIBLE AND THE YOUTUBE VIDEOS DID NOT HELP AT ALL!!!!
> 
> When I FINALLY got to run the scrape, I get the error message "Failed to resolve 'fyp.ebay.com' ([Errno 11001]" something is going on with ebay to where it won't even run anything else. I am so defeated. Just take this crap down at this point, jesus christ...unless someone knows how ti fix it.

U can comment 538 line and it will work without ebay scraper

**Comment by ghost** [comment]
Comment on what though…is what I’m asking. Like where do you type it…

**Comment by martinvigo** [comment]
@kybrbie probably reading the README helps... I'll post the relevant part here for you...

"IMPORTANT: *email2phonenumber is a proof-of-concept tool I wrote during my research on new OSINT methodologies to obtain a target's phone number. The supported services (Ebay, Lastpass, Amazon and Twitter) have long added protections to protect from these type of scraping like having to receive a code over email first or simply adding captchas. There are of course many other sites that are still leaking phone number digits but I am focused on other research projects. Feel free to submit pull request if you want to add support for new sites."

Also, you may think for some reason that I am getting paid for this or something given your attitude and tone of your message. Maybe you want to try and appreciate researchers work rather than just complaining and being rude?

@Weffy61 kudos to you for your patience and trying to help even in disrespectuful scenarios like this

**Comment by ghost** [comment]
No one thinks you are getting paid so no need to be a rude piece of shit.
Like I said, I fooled with this for over 6 hours and could not figure
anything out. It was extremely frustrating but I no longer care.
